export type RoleTemplatePromptInput = {
  domainSlugs: string[];
  skillSlugs: string[];
  ruleSlugs: string[];
};

function formatExampleSlugs(slugs: string[], fallback: string, limit = 8): string {
  const unique = Array.from(new Set(slugs.map((item) => item.trim()).filter(Boolean)));
  return unique.slice(0, limit).join(" / ") || fallback;
}

export function buildRoleTemplatePrompt({
  domainSlugs,
  skillSlugs,
  ruleSlugs,
}: RoleTemplatePromptInput): string {
  const domainExamples = formatExampleSlugs(domainSlugs, "XXX-domain");
  const skillExamples = formatExampleSlugs(skillSlugs, "XXX-skill");
  const ruleExamples = formatExampleSlugs(ruleSlugs, "XXX-rule");

  return [
    "请为本项目生成一个可直接用于“专家管理”后台的新专家定义，专家名称统一先用“XXX专家”占位。",
    "",
    "请严格遵守下面约束：",
    "1. 只输出结果，不要解释生成思路，不要写免责声明。",
    "2. 所有暂不确定的信息统一使用 XXX 占位，不要擅自脑补。",
    "3. 后台 JSON 里的 `slug` 必须等于 Markdown frontmatter 里的 `id`，并使用 kebab-case。",
    "4. 角色 frontmatter 必须覆盖：`id`、`name`、`status`、`domains`、`description`、`triggers`、`preferred_skills`、`reads`、`writes`、`handoff_to`。",
    "5. 正文必须覆盖：`角色定位`、`工作原则`、`必做步骤`、`执行契约`、`输出标准`、`禁止事项`、`交接说明`。",
    "6. 后台扩展字段必须补齐：`author`、`publishStatus`、`roleStatus`、`supportedProfiles`、`tags`、`skillSlugs`、`ruleSlugs`、`domainSlugs`。",
    "7. `roleStatus` 只允许 `draft` / `active` / `planned`；`publishStatus` 只允许 `draft` / `published`。",
    "8. `domainSlugs` 要与 Markdown 中的 `domains` 对齐；`skillSlugs` 应尽量与 `preferred_skills` 对齐。",
    "9. 如果某项未知，保留 XXX，但不要省略字段，也不要新增当前项目结构里没有的新字段。",
    "",
    "当前项目可参考 slug（节选）：",
    `- domains: ${domainExamples}`,
    `- skills: ${skillExamples}`,
    `- rules: ${ruleExamples}`,
    "",
    "请按下面顺序输出，且不要追加多余说明：",
    "",
    "## 1. 字段核对清单",
    "使用 Markdown 表格列出字段名、是否必填、作用、示例值。至少覆盖这些字段：",
    "`slug`、`name`、`author`、`publishStatus`、`roleStatus`、`description`、`supportedProfiles`、`tags`、`domains`、`triggers`、`preferred_skills`、`reads`、`writes`、`handoff_to`、`rolePositioning`、`workingPrinciples`、`requiredSteps`、`executionContract`、`outputStandard`、`prohibitedActions`、`handoffNotes`、`skillSlugs`、`ruleSlugs`、`domainSlugs`。",
    "",
    "## 2. 后台表单 JSON",
    "请输出一个可直接给后台录入人员参考的 JSON，字段模板如下：",
    "```json",
    "{",
    '  "name": "XXX专家",',
    '  "slug": "xxx-expert",',
    '  "author": "XXX",',
    '  "description": "用一句话说明 XXX专家 的职责边界",',
    '  "publishStatus": "draft",',
    '  "roleStatus": "active",',
    '  "supportedProfiles": ["react"],',
    '  "tags": ["XXX"],',
    '  "triggers": ["XXX-trigger"],',
    '  "preferredSkills": ["XXX-skill"],',
    '  "reads": ["XXX-input"],',
    '  "writes": ["XXX-output"],',
    '  "handoffTo": ["XXX-next-role"],',
    '  "rolePositioning": "XXX",',
    '  "workingPrinciples": ["XXX"],',
    '  "requiredSteps": ["XXX"],',
    '  "executionContract": "XXX",',
    '  "outputStandard": "XXX",',
    '  "prohibitedActions": ["XXX"],',
    '  "handoffNotes": "XXX",',
    '  "skillSlugs": ["XXX-skill"],',
    '  "ruleSlugs": ["XXX-rule"],',
    '  "domainSlugs": ["XXX-domain"]',
    "}",
    "```",
    "",
    "## 3. 可导入 Markdown 专家文件",
    "请再输出一份可导入的 Markdown 专家文件，格式如下：",
    "```md",
    "---",
    "id: xxx-expert",
    "name: XXX专家",
    "status: active",
    "domains:",
    "  - XXX-domain",
    "description: 用一句话说明 XXX专家 的职责边界",
    "triggers:",
    "  - XXX-trigger",
    "preferred_skills:",
    "  - XXX-skill",
    "reads:",
    "  - XXX-input",
    "writes:",
    "  - XXX-output",
    "handoff_to:",
    "  - XXX-next-role",
    "---",
    "",
    "# XXX专家",
    "",
    "## 角色定位",
    "XXX",
    "",
    "## 工作原则",
    "- XXX",
    "",
    "## 必做步骤",
    "1. XXX",
    "",
    "## 执行契约",
    "XXX",
    "",
    "## 输出标准",
    "XXX",
    "",
    "## 禁止事项",
    "- XXX",
    "",
    "## 交接说明",
    "XXX",
    "```",
    "",
    "额外要求：",
    "- 字段不要缺失。",
    "- 如果没有把握，就保留 XXX。",
    "- 不要生成与当前项目结构无关的新字段。",
  ].join("\n");
}
